---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-lifecycle-demo
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    path: manifests/application
    repoURL: https://github.com/scottd018/rosa-application-lifecycle-demo
  syncPolicy:
    automated:
      selfHeal: true
