---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: demo-github
  namespace: demo-pipeline
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev/v1alpha1
          params:
            - name: eventTypes
              value:
                - push
      bindings:
        - ref: demo-github
      template:
        ref: demo-github
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: demo-github
  name: demo-github
  namespace: demo-app
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: ""
    name: el-demo-github
