---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-install-tools
  namespace: demo
spec:
  params:
    - name: knativeVersion
      type: string
      default: v1.9.0
      description: |
        The version of kn to install
    - name: knativeFuncVersion
      type: string
      default: v1.9.0
      description: |
        The version of the kn func plugin to install
  steps:
    - name: setup-install-knative-tools
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        set -e
        dnf install -y wget
        mkdir -p /workspace/bin
        wget https://github.com/knative/client/releases/download/knative-$(params.knativeVersion)/kn-linux-amd64 -O /workspace/bin/kn
        chmod +x /workspace/bin/kn
        wget https://github.com/knative/func/releases/download/knative-$(params.knativeFuncVersion)/func_linux_amd64 -O /workspace/bin/kn-func
        chmod +x /workspace/bin/kn-func
  workspaces:
    - name: workspace
      mountPath: /workspace
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-git-clone
  namespace: demo
spec:
  params:
    - name: gitRepo
      type: string
      description: |
        The url of the public git repo to clone
    - name: gitRepoDestination
      type: string
      default: /workspace/code
      description: |
        The destination folder inside of the workspace where the repo is downloaded
  steps:
    - name: setup-git-clone
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        set -e
        dnf install -y git
        git clone $(params.gitRepo) $(params.gitRepoDestination)
  workspaces:
    - name: workspace
      mountPath: /workspace
