---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-knative-function
  namespace: demo
spec:
  params:
    - name: workingDir
      type: string
      default: /workspace
      description: |
        Working directory where work is performed.
    - name: workingSubDir
      type: string
      default: code
      description: |
        Working sub-directory where code is downloaded and acted upon.
    - name: workingDemoDir
      type: string
      default: demo
      description: |
        Working sub-directory within workingSubDir that contains the knative function code.
  workspaces:
    - name: persistent-storage
    - name: image-storage
  tasks:
    # setup
    - name: setup-tools
      taskRef:
        name: setup-install-tools
      workspaces:
        - name: workspace
          workspace: persistent-storage
      params:
        - name: knativeBinaryLocation
          value: "$(params.workingDir)/bin"
    - name: setup-git
      taskRef:
        name: setup-git-clone
      workspaces:
        - name: workspace
          workspace: persistent-storage
      runAfter:
        - setup-tools
      params:
        - name: gitRepo
          value: https://github.com/scottd018/rosa-application-lifecycle-demo.git
        - name: gitRepoDestination
          value: "$(params.workingDir)/$(params.workingSubDir)"

    # unit test
    - name: unit-test
      taskRef:
        name: test-unit-go
      workspaces:
        - name: workspace
          workspace: persistent-storage
      runAfter:
        - setup-git
      params:
        - name: goTestDirectory
          value: "$(params.workingDir)/$(params.workingSubDir)/$(params.workingDemoDir)"

    # e2e test
    - name: e2e-test
      taskRef:
        name: test-e2e-knative
      workspaces:
        - name: workspace
          workspace: persistent-storage
        - name: images
          workspace: image-storage
      runAfter:
        - unit-test
      params:
        - name: knativeDirectory
          value: "$(params.workingDir)/$(params.workingSubDir)/$(params.workingDemoDir)"
