---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-lifecycle-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/console
    repoURL: https://github.com/siamaksade/openshift-gitops-getting-started
    targetRevision: "1.1"
  syncPolicy:
    automated:
      selfHeal: true
